version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend_node:3001

  backend_node:
    build:
      context: ./backend/node
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend/node:/usr/src/app
    stdin_open: true
    tty: true
